// Copyright 2019 Google LLC
//
// Licensed under the the Apache License v2.0 with LLVM Exceptions (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://llvm.org/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

pipeline {
    agent any
    triggers {
        pollSCM 'H H/2 * * *'
    }
    environment {
        BUILD_ID='${env.JOB_BASE_NAME}-${env.BUILD_NUMBER}'
        TARGET_DIR='/mnt/nfs/results/${BUILD_ID}'
    }
    stages {
        stage("git checkout"){
            steps {
                git url: 'https://github.com/llvm/llvm-project.git'
                sh 'git clean -fdx'
                sh 'mkdir -p llvm-premerge-checks'
                dir("llvm-premerge-checks")
                {
                    git url: 'https://github.com/google/llvm-premerge-checks.git'
                }
            }            
        }
        stage('CMake') {
            steps {
                sh 'llvm-premerge-checks/scripts/run_cmake.sh'
            }
        }
        stage('ninja all') {
            steps {
                sh 'llvm-premerge-checks/scripts/run_ninja.sh all'
            }
        }
        stage('ninja check') {
            steps {
                sh 'llvm-premerge-checks/scripts/run_ninja.sh check'
            }
        }
        stage('ninja check-all') {
            steps {
                sh 'llvm-premerge-checks/scripts/run_ninja.sh check-all'
            }
        }
    }
    post { 
        always { 
            echo 'Console log is available at https://results.new.llvm-mgerge-guards/${env.BUILD_ID}'
            dir('${env.TARGET_DIR}') {
                // copy console log to result folder
                sh 'wget -qO console-log.txt http://jenkins-ui.jenkins.svc.cluster.local:8080/job/${JOB_BASE_NAME}/${BUILD_NUMBER}/consoleText'
            }
        }
    }
}