// Copyright 2019 Google LLC
//
// Licensed under the the Apache License v2.0 with LLVM Exceptions (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://llvm.org/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

pipeline {
    agent any
    parameters {
        string(name: 'DIFF_ID')
        string(name: 'PHID')
    }
    stages {
        stage("git checkout"){
            steps {
                git url: 'https://github.com/llvm/llvm-project.git'
                sh 'mkdir -p llvm-premerge-checks'
                dir("llvm-premerge-checks")
                {
                    git url: 'https://github.com/google/llvm-premerge-checks.git'
                }
            }            
        }
        stage('CMake') {
            steps {
                sh 'llvm-premerge-checks/scripts/run_cmake.sh'
            }
        }
        stage('ninja check-all') {
            steps {
                sh 'llvm-premerge-checks/scripts/run_ninja_check-all.sh'
            }
            }
        }
    }
}