#TODO replace network, subnetwork, region, zone and image with the placeholders. Trigger this from the terraform ?
#windows-server-2019-dc-core-for-containers-v20230113
#windows-server-2019-dc-for-containers-v20230113
#TODO get latest image in family
#TODO check different machine types and timings
steps:
  - name: 'gcr.io/${PROJECT_ID}/windows-builder'
    args: ['--image','windows-cloud/global/images/windows-server-2019-dc-core-for-containers-v20230113',
          '--network', 'vpc-network',
          '--subnetwork', 'subnetwork',
          '--region', 'europe-west3',
          '--zone', 'europe-west3-c',
          '--machineType', "n2-standard-16",
          '--diskType', 'pd-ssd',
          '--command', 'gcloud auth configure-docker --quiet && docker build -t gcr.io/${PROJECT_ID}/buildkite-premerge-windows:latest . && docker push gcr.io/${PROJECT_ID}/buildkite-premerge-windows:latest']
timeout: 7200s