// Copyright 2019 Google LLC
//
// Licensed under the the Apache License v2.0 with LLVM Exceptions (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://llvm.org/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

pipeline {
    agent { label 'windows' }
    
    // TODO(christian.kuehnel): re-enable scheduled builds 
    // once the pipeline works properly
    //triggers {
    //    pollSCM '0 H/2 * * *'
    //}
    // enable timestaps for getting execution times
    options { timestamps () }
    environment {
        BUILD_ID = "${JOB_BASE_NAME}-${BUILD_NUMBER}"
        TARGET_DIR = "/mnt/nfs/results/${BUILD_ID}"
        SCRIPT_DIR = "${WORKSPACE}/llvm-premerge-checks/scripts"
        RESULT_DIR = "C:\\results\\${BUILD_ID}"
    }
    stages {
        stage("git checkout"){
            steps {
                dir("llvm-premerge-checks")
                {
                    git url: 'https://github.com/google/llvm-premerge-checks.git'
                }
                dir("llvm-project"){
                    powershell "${SCRIPT_DIR}/git_checkout.ps1"
                    powershell 'New-Item -ItemType Directory -Force -Path ${TARGET_DIR}'
                    powershell 'New-Item -ItemType Directory -Force -Path ${RESULT_DIR}'
                }
            }            
        }
        stage('CMake') {
            steps {
                dir("llvm-project"){
                    powershell "${SCRIPT_DIR}/run_cmake.ps1"
                }
            }
        }
        stage('ninja all') {
            steps {
                dir("llvm-project"){
                    powershell "${SCRIPT_DIR}/run_ninja.ps1 all"
                }
            }
        }
        stage('ninja check-all') {
            steps {
                dir("llvm-project"){
                    powershell "${SCRIPT_DIR}/run_ninja.ps1 check-all"
                }
            }
        }
    }
/*
    post { 
        always { 
            echo "Console log is available at https://results.new.llvm-merge-guard.org/${BUILD_ID}"
            dir("${env.TARGET_DIR}") {
                // copy console log to result folder
                bat "wget -qO console-log.txt http://jenkins-ui.jenkins.svc.cluster.local:8080/job/${JOB_BASE_NAME}/${BUILD_NUMBER}/consoleText"
                // TODO: move all file copy operations here
            }
        }
    }
*/

}