#!/bin/bash
# Copyright 2023 Google LLC
#
# Licensed under the the Apache License v2.0 with LLVM Exceptions (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# See https://buildkite.com/docs/agent/v3/hooks#job-lifecycle-hooks
# The `post-checkout` hook runs after checkout.

# Pull changes from origin/main so that diff origin/main...HEAD will show a
# correct diff of Pull Requests that have multiple commits.

set -euo pipefail
git fetch origin main:main
