@startuml
component phabricator
component buildkite

node github {
 component "llvm-project"
 component "llvm-project fork"
 component "llvm-premerge-checks"
}

node "GCP" {
 component "buildkite agents"
 component "phab-proxy"
}


[phabricator] --> [phab-proxy]
[phab-proxy] --> [buildkite]
[buildkite] <-- [buildkite agents]
[buildkite agents] <-- [llvm-project]
[buildkite agents] <--> [llvm-project fork]
[buildkite agents] --> [phabricator]
[buildkite agents] <-- [llvm-premerge-checks]
@enduml
