# Copyright 2021 Google LLC
#
# Licensed under the the Apache License v2.0 with LLVM Exceptions (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkite-service-agents-test
  namespace: buildkite
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: buildkite-service-agents
  template:
    metadata:
      labels:
        app: buildkite-service-agents
    spec:
      containers:
        - name: runner
          image: gcr.io/llvm-premerge-checks/buildkite-linux:latest
          resources:
            limits:
              cpu: 2
              memory: 5Gi
            requests:
              cpu: 1.5
              memory: 5Gi
          volumeMounts:
            - name: github-ssh
              mountPath: /mnt/ssh
          env:
            - name: BUILDKITE_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: buildkite-agent-token
                  key: token
            - name: POD_NAME
              valueFrom:
                fieldRef:
                 fieldPath: metadata.name
            - name: BUILDKITE_AGENT_TAGS
              value: "queue=service-test,name=$(POD_NAME)"
            - name: BUILDKITE_BUILD_PATH
              value: "/var/lib/buildkite-agent/builds"
            - name: CONDUIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: conduit-api-token
                  key: token
            - name: BUILDKITE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: buildkite-api-token-readonly
                  key: token
      volumes:
        - name: github-ssh
          secret:
            secretName: github-ssh
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      terminationGracePeriodSeconds: 60